yarnPath: .yarn/releases/yarn-3.2.0-rc.9.cjs

pnpFallbackMode: all

packageExtensions:
  "@aws-crypto/sha256-browser@*":
    dependencies:
      "@aws-sdk/util-utf8-browser": "*"
  "@aws-amplify/api@*":
    dependencies:
      # ./.yarn/cache/@aws-amplify-api-npm-3.2.30-cfc9d17a70-ef156f3d1b.zip/node_modules/@aws-amplify/api/lib-esm/API.js
      "@aws-amplify/auth": "*"
      # idem
      "@aws-amplify/cache": "*"
      # idem
      "@aws-amplify/core": "*"
  "@aws-amplify/datastore@*":
    dependencies:
      # idem
      "@aws-amplify/cache": "*"
      # ./.yarn/cache/@aws-amplify-datastore-npm-<version+hash>.zip/node_modules/@aws-amplify/datastore/lib-esm/util.js
      "crypto-js": "*"
      # ./.yarn/cache/@aws-amplify-datastore-npm-<version+hash>.zip/node_modules/@aws-amplify/datastore/lib/authModeStrategies/multiAuthStrategy.js
      "@aws-amplify/api-graphql": "*"
      # cries inside
      "@types/node": "*"
  "@aws-amplify/storage@*":
    dependencies:
      # ./.yarn/cache/@aws-amplify-storage-npm-<version+hash>.zip/node_modules/@aws-amplify/storage/lib-esm/providers/AWSS3ProviderManagedUpload.js
      "@aws-sdk/fetch-http-handler": "*"
      # ./.yarn/cache/@aws-amplify-storage-npm-<version+hash>.zip/node_modules/@aws-amplify/storage/lib-esm/providers/axios-http-handler.js
      "@aws-sdk/protocol-http": "*"
      # idem
      "@aws-sdk/querystring-builder": "*"
  babel-preset-react-app@*:
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"
